name: My First Workflow # 워크플로우 고유 이름
on: [push, fork] # 트리거
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List and Read file
        run: |
          echo "Hello, world!"
          ls -ltra
          cat README.md

      # - name: List files
      #   run: ls

      # - name: Read file
      #   run: cat README.md
